import 'package:app_876/core/constants/assets.dart';

List<String> serviceImages = [
  serviceListImage1,
  serviceListImage2,
  serviceListImage3,
  serviceListImage4,
  serviceListImage5,
  serviceListImage6,
  serviceListImage7,
  serviceListImage8,
  serviceListImage9,
  serviceListImage10,
  serviceListImage11,
  serviceListImage12,
  serviceListImage13,
  serviceListImage14,
  serviceListImage15,
  serviceListImage16,
  serviceListImage17,
  serviceListImage18,
  // serviceListImage19,
  // serviceListImage20,
  // serviceListImage21,
];

final List<String> serviceTitles = [
  'Adult Bars Entertainment',
  'Architect',
  'Barbers',
  'Auto Mechanic',
  'Beautician',
  'Construction',
  'Boutiques',
  'Dentist',
  'Designer Stylist',
  'Doctors',
  'Gym',
  'Hair Stylist',
  'Hardware',
  'Hotels',
  'Message Therapist',
  'Night Club',
  'Personal Trainer',
  'Realtors',
];
